Content-Type: multipart/mixed; boundary="===============FTNT-VM==============="
MIME-Version: 1.0

--===============FTNT-VM===============
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="config"

config system global
    set hostname "${vm_name}"
end

exec vm-license ${license_flex}

--===============FTNT-VM===============
